### ISSUE TITLE
Flickering observed on PLP when SSR is enabled (2.0.8)

### ISSUE THREAD

**Issue by VGRAJED** [SAP/spartacus#10388]
## Environment
Spartacus: Version 2.0.8
Browser: Google Chrome Version 87.0.4280.88 (Official Build) (x86_64)
OS: Mac OS Catalina 10.15.7

## Steps to Reproduce
Follow steps on #6337

### Observed behaviour
On SSR: When dispatching the action `CmsActions.LOAD_CMS_PAGE_DATA_SUCCESS`, the respective reducer stores the page by using the `pageId` as key (for example, `productList`).

On CSR: When navigating from SSR to CSR, the selector `CmsSelectors.getPageStateIndexLoaderState` tries to find the page by using the pageContext ID (`{ id: "my-category-1", type: "CategoryPage"}`). Since it will not find the object in the cms  `entities`, it will generate a new request to `/cms/pages`, causing a flicker.

![image](https://user-images.githubusercontent.com/59665342/101966250-05747580-3be5-11eb-9f4e-4b6d5929f115.png)

**Comment by dunqan** [comment]
Hi @VGRAJED , thanks for the issue. 

Can you confirm if you still observe this on 2.1.4?

2.1.4 has fix regarding flickering on PLP or search page, caused by the logic that delayed emission of results model, even if it was already available (https://github.com/SAP/spartacus/commit/0ba3f5814e0a54696e89877c315c9be1beac82a1#diff-e20603ba48425a78cb7a8943da13c3a380a85079c1169caccfd805c7225eaea1R101).

Additional note: page data will be reloaded on the csr side anyway, but should be done after page is displayed and not cause flickering. To disable this behavior, you can set `routing.loadStrategy` to `RouteLoadStrategy.ONCE`.

**Comment by VGRAJED** [comment]
Hi @dunqan, I am currently trying it out with 2.1.4, but I am getting an error at `cms-components.service.ts`: `this.featureModules.hasFeatureFor` where `this.featureModules` is undefined.

**Comment by dunqan** [comment]
Hi @VGRAJED, it's strange, are you able to share more details about how you upgraded to 2.1.4? Did you bump versions to 2.1.4 for all the Spartacus libs? 
Also, do you have a custom `CmsComponentService`?

**Comment by dunqan** [comment]
Hi @VGRAJED, I'm closing this for now, as there was one more fix merged related to flickering, not strictly related to this one, but also included a fix for the issue you were reporting (however, it should only happen if you were overwritten `CmsComponentsService` in the first place, which is unlikely). 

I'm happy to reopen it if you'll confirm this issue in 2.1.5, but we were not able to reproduce it at the moment. 

2.1.5 is scheduled to be released later today or tomorrow morning.

**Comment by VGRAJED** [comment]
Hi @dunqan, I just tested with 2.1.5 and it seems to have been resolved, that's great!

Does this version add any "breaking" change that will impact other aspects on the site? I am aware it was an upgrade of 2.0.x to 2.1.x, which shouldn't introduce any breaking change, but there may be something that is not easily spotted my looking at the docs.

Thank you.

**Comment by VGRAJED** [comment]
Hi @dunqan, sorry for the late reply. We tried using version 2.1.5 and the issue still happens. We do have a custom `CmsComponentService`.
