### ISSUE TITLE
Wrong canonical url in product page (ip instead of domain)

### ISSUE THREAD

**Issue by alvteren** [SAP/spartacus#14711]
**Describe the bug**
I have canonical in product page like `https://127.0.0.1:4200/product/klej-moment-super`, but canonical in home page `https://domain.com/`

**Tell us the version of Spartacus**
- Library version: 4

**To Reproduce**
1. In server.ts I have `server.set('trust proxy', 'loopback');`
2. Open url https://domain.com/product/klej-moment-super
3. See canonical url https://127.0.0.1:4200/product/klej-moment-super

**Additional context**
I think if in RoutingService method getFullUrl instead of:
```typescript
getFullUrl(commands: UrlCommands, extras?: NavigationExtras) {
    return `${this.winRef.document.location.origin}${this.getUrl(
      commands,
      extras
    )}`;
  }
```

replace to:
```typescript
getFullUrl(commands: UrlCommands, extras?: NavigationExtras) {
    return `${this.winRef.location.origin}${this.getUrl(
      commands,
      extras
    )}`;
  }
```

It will work correct

**Comment by Xymmer** [comment]
investigate what's happening and fix in 5.0 and backport to 4.x
kate will try to repro

**Comment by Xymmer** [comment]
hi, closing as can't repro, seems it was fixed by at least 4.2 or earlier

**Comment by yogeshmali99** [comment]
@Xymmer I can still see the issue with PDP page with Spartacus 6.5
