### ISSUE TITLE
on upgrade to Spartacus 4.3, selectiveCartService cannot find userAccountFacade

### ISSUE THREAD

**Issue by annayang-seidor** [SAP/spartacus#15703]
**Describe the bug**
After upgrading from Spartacus ~3.4.4 to ~4.3, the webpage throws error: 
Node version is from v12 to v14.17.5
```
core.mjs:6485 ERROR Error: Cannot get a user. Install `@spartacus/user` library which provides required services.
    at UserService.get (spartacus-core.js:11754:15)
    at new SelectiveCartService (spartacus-core.js:11817:30)
    at Object.SelectiveCartService_Factory [as factory] (spartacus-core.js:11922:1)
   ...
```

**To Reproduce**
1. upgrade from Spartacus ~3.4.4 to ~4.3, use package json as follows:
```
"dependencies": {
    "@angular/core": "~10.2.5",
    /* ... */    
    "@spartacus/assets": "~3.4.4",
    "@spartacus/core": "~3.4.4",
    "@spartacus/storefront": "~3.4.4",
    "@spartacus/styles": "~3.4.4",
    "rxjs": "~6.5.4",
    "zone.js": "^0.11.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1002.4",
    "@angular/cli": "~10.2.3",
    "@angular/compiler-cli": "~10.2.5",
    "@spartacus/schematics": "~3.4.4",
    /* ... */
    "typescript": "~4.0.7"
  }
```

New package json: 

```

  "dependencies": {
    "@angular/animations": "^13.3.4",
    "@angular/cdk": "^12.2.13",
    "@angular/common": "~13.3.4",
    "@angular/compiler": "~13.3.4",
    "@angular/core": "~13.3.4",
    "@angular/forms": "~13.3.4",
    "@angular/localize": "~13.3.4",
    "@angular/material": "^12.2.13",
    "@angular/platform-browser": "~13.3.4",
    "@angular/platform-browser-dynamic": "~13.3.4",
    "@angular/router": "~13.3.4",
    "@angular/service-worker": "~13.3.4",
    "@fortawesome/angular-fontawesome": "^0.8.1",
    "@fortawesome/fontawesome-free": "^5.15.4",
    "@fortawesome/fontawesome-svg-core": "^1.2.32",
    "@fortawesome/free-brands-svg-icons": "^5.15.1",
    "@fortawesome/free-solid-svg-icons": "^5.15.1",
    "@ng-bootstrap/ng-bootstrap": "^10.0.0",
    "@ng-select/ng-select": "^7.4.0",
    "@ngrx/effects": "~13.1.0",
    "@ngrx/router-store": "~13.1.0",
    "@ngrx/store": "~13.1.0",
    "@spartacus/asm": "^4.3.1",
    "@spartacus/assets": "~4.3.1",
    "@spartacus/cart": "^4.3.3",
    "@spartacus/checkout": "^4.3.1",
    "@spartacus/core": "^4.3.3",
    "@spartacus/product": "^3.4.10",
    "@spartacus/qualtrics": "^4.3.1",
    "@spartacus/storefinder": "4.3.1",
    "@spartacus/storefront": "~4.3.1",
    "@spartacus/styles": "~4.3.1",
    "@spartacus/user": "4.3.3",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.3.3",
    "@angular/cli": "~13.3.3",
    "@angular/compiler-cli": "~13.3.4",
    "@spartacus/schematics": "~4.3.1",
    /* ... */   
    "typescript": "~4.6.3"
  }
```

**Expected behavior**
Expected no error

**Screenshots**
From screenshot, it looks like the userAccountFacade has not been injected, although `@spartacus/user` has already been installed

![upgrade-error_2022-5-4](https://user-images.githubusercontent.com/89838642/166622253-d3d11a40-53e0-45a6-810e-42cc5d7ae641.png)

![2022-05-03](https://user-images.githubusercontent.com/89838642/166622237-427272f4-7728-4516-a524-743ef595d324.png)

**Desktop (please complete the following information):**
 - OS: [linux]
 - Browser [vivaldi, firefox, chrome]
 - Version [Ubuntu 20]

**Additional context**
The following error was thrown when I try to add `@spartacus/user` package with `ng`
(with `yarn add` or `npm install` it throws no error)
The first one was when I have already installed the package,
The second was when I have manually removed the package and install `@spartacus/user` again

![image](https://user-images.githubusercontent.com/89838642/166622711-ea012861-4f89-4ec5-a4c5-02ed415a4152.png)

**Comment by Platonn** [comment]
Spartacus 4.0 supports only Angular 12, but not v13 yet. Please use Angular v12 packages.
This should solve the error when installing `ng add @spartacus/user`: `"Must use import to load ES Module..."`
Please let us know in case of any further problems.

PS. The support for Angular 13 is planned in the future, in Spartacus 5.0

**Comment by annayang-seidor** [comment]
Hello Platonn,
Thank you for your info. 
I have downgraded it to Angular ~12.0.5 however the problem persists
I was wondering if there's any way I can override the SelectiveCartService or UserService? In that way I might be able to inject the UserAccountFacade to the right place.

**Comment by annayang-seidor** [comment]
I will update my own issue
This error can be resolved by overriding the UserService with the following code in `spartacus-configuration.module.ts`:

```
@NgModule({
  declarations: [],
  imports: [],
  providers: [
    {
      provide: UserService,
      useClass: UserAccountService,
    }
  ]
})
```

**Comment by Platonn** [comment]
Did you make sure to also downgrade other angular's family packages like `@angular-devkit/schematics`, `@schematics/angular`, etc?

btw. When upgrading from Spartacus 3.x to 4.x, did you follow the guidelines https://sap.github.io/spartacus-docs/updating-to-version-4/ ?

**Comment by annayang-seidor** [comment]
Hi Platonn,
Yes I did. this is the package.json content I've been using
I followed the upgrade guide but since angular reminded me to upgrade to 13 when I ran `ng upgrade`, I did what it told me to do
Proven that was not so wise to do so hahaha

Since there are many other packages, I also update them to fit at least compatible version. But for peer dependencies I did not change them

```
{
  "dependencies": {
    "@angular/animations": "~12.0.5",
    "@angular/cdk": "12.2.13",
    "@angular/common": "~12.0.5",
    "@angular/compiler": "~12.0.5",
    "@angular/core": "~12.0.5",
    "@angular/forms": "~12.0.5",
    "@angular/material": "12.2.13",
    "@angular/platform-browser": "~12.0.5",
    "@angular/platform-browser-dynamic": "~12.0.5",
    "@angular/router": "~12.0.5",
    "@angular/service-worker": "^12.0.5",
    "@fortawesome/angular-fontawesome": "^0.8.1",
    "@fortawesome/fontawesome-free": "^5.15.4",
    "@fortawesome/fontawesome-svg-core": "^1.2.32",
    "@fortawesome/free-brands-svg-icons": "^5.15.1",
    "@fortawesome/free-solid-svg-icons": "^5.15.1",
    "@ng-bootstrap/ng-bootstrap": "^10.0.0",
    "@ng-select/ng-select": "^7.0.1",
    "@ngrx/effects": "^12.1.0",
    "@ngrx/router-store": "^12.1.0",
    "@ngrx/store": "^12.1.0",
    "@spartacus/asm": "^4.3.1",
    "@spartacus/assets": "~4.3.1",
    "@spartacus/cart": "^4.3.3",
    "@spartacus/checkout": "^4.3.1",
    "@spartacus/core": "4.3.3",
    "@spartacus/product": "^3.4.10",
    "@spartacus/qualtrics": "^4.3.1",
    "@spartacus/storefinder": "4.3.1",
    "@spartacus/storefront": "~4.3.1",
    "@spartacus/styles": "~4.3.1",
    "@spartacus/user": "4.3.3",
    "angular-oauth2-oidc": "^10.0.1",
    "animate.css": "^4.1.1",
    "bootstrap": "^4.5.0",
    "bootstrap-select": "^1.13.18",
    "i18next": "^20.6.1",
    "i18next-http-backend": "^1.4.0",
    "i18next-xhr-backend": "^3.2.2",
    "jQuery": "^1.7.4",
    "jquery": "^3.6.0",
    "ngx-infinite-scroll": "10.0.1",
    "ngx-sharebuttons": "9.0.0",
    "ngx-toastr": "14.3.0",
    "rxjs": "~6.6.7",
    "swiper": "6.6.2",
    "tslib": "^2.1.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.2.17",
    "@angular-devkit/schematics": "^12.0.5",
    "@angular/cli": "~12.0.5",
    "@angular/compiler-cli": "~12.0.5",
    "@angular/localize": "12.0.5",
    "@spartacus/schematics": "~4.3.1",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "http-server": "^14.0.0",
    "husky": "^4.3.0",
    "install-peers-cli": "^2.2.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.19",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "prettier": "^2.6.2",
    "pretty-quick": "^3.1.0",
    "protractor": "~7.0.0",
    "typescript": "~4.2.3"
  }
}
```
