### ISSUE TITLE
In 2.0, when using Safari, images are stretched when loaded from a server [need to backport fix to 2.0]

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#8713]
Description update Aug 25:
This was fixed in develop after 2.0 maintenance was created, but wasn't merged to maintenance at the time. It was also not backported, see history below.
This ticket is just about backporting the fix to 2.0.
----
Go to our ccv2 with Safari or ios
https://jsapps.c432wmya2v-teamspart1-s2-public.model-t.myhybris.cloud/electronics-spa/en/USD/
or http://cx-qa16181492.eastus.cloudapp.azure.com:4200/electronics-spa/en/USD/
Some images are stretched
Doesn't happen with Chrome or Firefox
![image](https://user-images.githubusercontent.com/4998145/91083780-dd9ed900-e618-11ea-8078-42a67a523f62.png)

CCv2 is using 2.0.... something, from 3-4 weeks ago.
Also happens in latest develop when viewing on a server, but not when Spartacus app is run locally and pointing to public backend server.

Not really related to #8681

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-08-24 at 3 23 20 PM](https://user-images.githubusercontent.com/46171897/91089500-a3860500-e621-11ea-98ab-416dd76b1b08.png)

Similar behaviour seen with release/2.0.0 and latest develop branch.

**Comment by developpeurweb** [comment]
@giancorderoortiz 
I fixed this back in May in https://github.com/SAP/spartacus/pull/7821
`develop` has the changes, but for some reason, the servers in this ticket **don't**, they're using old CSS.

**Comment by giancorderoortiz** [comment]
Servers where problem persists: 
1. qa (latest dev branch) -> http://cx-qa16181492.eastus.cloudapp.azure.com:4200/electronics-spa/en/USD/
2. demo (release 2.0.0) -> http://spartacus-demo.eastus.cloudapp.azure.com:31415/electronics-spa/en/USD/

both deployed with schematics.

**Comment by developpeurweb** [comment]
This is causing the problem:

![Screen Shot 2020-08-24 at 4 04 18 PM](https://user-images.githubusercontent.com/15113219/91090934-da5d1a80-e623-11ea-97de-76699a5e4901.png)

It was removed 3 months ago, but apparently it didn't make it to 2.0.0

![Screen Shot 2020-08-24 at 4 05 24 PM](https://user-images.githubusercontent.com/15113219/91090949-e2b55580-e623-11ea-8b98-cb5b2d610b22.png)

![Screen Shot 2020-08-24 at 4 13 39 PM](https://user-images.githubusercontent.com/15113219/91091679-f4e3c380-e624-11ea-8f1a-b5395d1ac7b4.png)

**Comment by Xymmer** [comment]
Reminder to fix in
Develop
2.1 maintenance
Also backport to 2.0

**Comment by tobi-or-not-tobi** [comment]
This is caused by #7737 and already fixed by #7821. We haven't back ported it to 2.0. it's debatable if we do that, we rather update ccv2 to 2.1 as soon as its out.

**Comment by Xymmer** [comment]
Repurposing ticket to backport to 2.0.

**Comment by giancorderoortiz** [comment]
Fixed. 
Minor 2.1.0
http://spartacus-dev2.eastus.cloudapp.azure.com:4200/electronics-spa/en/USD/
http://spartacus-dev2.eastus.cloudapp.azure.com:4200/apparel-uk-spa/en/GBP/
Patch 2.0.8
http://spartacus-dev2.eastus.cloudapp.azure.com:3200/electronics-spa/en/USD/
http://spartacus-dev2.eastus.cloudapp.azure.com:3200/apparel-uk-spa/en/GBP/
